### ISSUE TITLE
Palindrome Checker

### ISSUE THREAD

**Issue by ShoomanKhatri** [indra-kc/DSA#10]
Problem: Check if a given string or number reads the same forwards and backwards.

**Comment by BarryByte** [comment]
@indra-kc Please assign me this issue.

**Comment by Laxmi-KC** [comment]
Plz assigned this to me.

**Comment by indra-kc** [comment]
@Laxmi-KC  done

**Comment by indra-kc** [comment]
@BarryByte  complete another task and i will assigned to others.

**Comment by ShoomanKhatri** [comment]
completed
